version: v0.3.0

listeners:
  - type: model
    name: llm_proxy
    port: 12000

model_providers:
  - model: digitalocean/llama3.3-70b-instruct
    base_url: https://inference.do-ai.run
    provider_interface: openai
    access_key: $DO_MODEL_ACCESS_KEY
    default: true
